[programs.localnet]
claiming_factory = "6cJU4mUJe1fKXzvvbZjz72M3d5aQXMmRV2jeQerkFw5b"

[programs.devnet]
claiming_factory = "6cJU4mUJe1fKXzvvbZjz72M3d5aQXMmRV2jeQerkFw5b"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/gggg/.config/solana/devnet-wallet.json"
rpc = "https://devnet.helius-rpc.com/?api-key=9e363f6a-e17b-4c0f-81c0-6a2182332a53"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
